on: [ push, pull_request ]
name: flake8 linting
jobs:
    flake8:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - uses: actions/checkout@v2
            - run: pacman --noconfirm -Syu python python-pip
            - run: python -m pip install --upgrade pip
            - run: pip install flake8
            - name: Lint with flake8
              run: flake8