on: 
    pull_request:
        types: [opened, reopened]
    push:
        paths:
            '**'

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

name: pytest test validation
jobs:
    pytest:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
            options: --privileged -v /dev:/dev
            # --cap-add=MKNOD --device-cgroup-rule="b 7:* rmw"
        steps:
            - uses: actions/checkout@v2
            - run: pacman --noconfirm -Syu sudo python python-pip python-pydantic parted
            - run: python -m pip install --upgrade pip
            - run: ls -lah
            - run: pwd
            - run: pip install .
            - run: pip install pytest
            - name: Test with pytest
              run: python -m pytest